name: Stock Analysis Automation

on:
  schedule:
    - cron: '0 8 * * *'  # Chạy vào 8 giờ sáng mỗi ngày (UTC)
  workflow_dispatch:      # Cho phép bạn chạy thủ công từ giao diện GitHub

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Upgrade vnstock
      run: pip install --upgrade vnstock
      
    - name: Run analysis script
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        python main.py
